# file for specifying model parameters for the temperature robustness check
sampling_presets:
  llama-3.3-70b-low-temp: &llamalow
    temperature: 0.2
    top_p: 0.9 # default
    top_k: 0 #default
  llama-3.3-70b-high-temp: &llamahigh
    temperature: 1.2
    top_p: 0.9
    top_k: 0
  qwen-2.5-72b-low-temp: &qwenlow
    temperature: 0.2
    top_p: 0.8 # default
    top_k: 20 # default
  qwen-2.5-72b-high-temp: &qwenhigh
    temperature: 1.2
    top_p: 0.8
    top_k: 20

profiles:
  tester: # this is a test model, so we dont have to queue a large model on the HPC
    repo_id: unsloth/gemma-3-4b-it-unsloth-bnb-4bit
    quantization: bitsandbytes
    has_default_sampling_params: False
    sampling: *qwenhigh
  llama-3.3-70b-low-temp: 
    repo_id: unsloth/Llama-3.3-70B-Instruct-bnb-4bit
    quantization: bitsandbytes
    has_default_sampling_params: False
    sampling: *llamalow
  llama-3.3-70b-high-temp:
    repo_id: unsloth/Llama-3.3-70B-Instruct-bnb-4bit
    quantization: bitsandbytes
    has_default_sampling_params: False
    sampling: *llamahigh
  qwen-2.5-72b-low-temp: 
    repo_id: unsloth/Qwen2.5-72B-Instruct-bnb-4bit
    quantization: bitsandbytes
    has_default_sampling_params: False
    sampling: *qwenlow
  qwen-2.5-72b-high-temp: 
    repo_id: unsloth/Qwen2.5-72B-Instruct-bnb-4bit
    quantization: bitsandbytes
    has_default_sampling_params: False
    sampling: *qwenhigh
  