# models.yaml
# File specifying specific model params
sampling_presets:
  gpt20b: &gpt20b
    temperature: 1.0
    top_p: 1.0
  gpt9b: &gpt9b
    temperature: 1.0
    top_p: 1.0
  gemma4b: &gemma4b
    temperature: 1.0
    top_k: 64
    top_p: 0.95
  gemma27b: &gemma27b
    temperature: 1.0
    top_k: 64
    top_p: 0.95


profiles:
  llama-3.3-70b: # new
    repo_id: unsloth/Llama-3.3-70B-Instruct-bnb-4bit
    quantization: bitsandbytes
    has_default_sampling_params: True
  llama-3.1-8b: # new
    repo_id: unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit
    quantization: bitsandbytes
    has_default_sampling_params: True
  gpt-20b: # new
    repo_id: unsloth/gpt-oss-20b-unsloth-bnb-4bit 
    quantization: bitsandbytes
    has_default_sampling_params: False
    sampling: *gpt20b
  gpt-oss-9b: # new
    repo_id: mradermacher/gpt-oss-nano-GGUF
    quantization: gguf
    has_default_sampling_params: False
    sampling: *gpt9b
  qwen-2.5-72b: # new
    repo_id: unsloth/Qwen2.5-72B-Instruct-bnb-4bit
    quantization: bitsandbytes
    has_default_sampling_params: True
  qwen-2.5-7b: # old
    repo_id: unsloth/Qwen2.5-7B-Instruct-bnb-4bit
    quantization: bitsandbytes
    has_default_sampling_params: True
  gemma-3-4b: # new
    repo_id: unsloth/gemma-3-4b-it-unsloth-bnb-4bit
    quantization: bitsandbytes
    has_default_sampling_params: False
    sampling: *gemma4b
  gemma-3-27b: # new
    repo_id: unsloth/gemma-3-27b-it-bnb-4bit
    quantization: bitsandbytes
    has_default_sampling_params: False
    sampling: *gemma27b
  


  
